#!/usr/bin/env python

"""
Render README.md -- the GitHub profile page -- from README.md.in and
../data/yaml/profiles.yaml.

GitHub serves README.md straight from the default branch of this repository, so
it is a committed artifact rather than throwaway build output: there is no
deploy step, and a push is the publish.

That is why the hand-written prose lives in README.md.in rather than in
README.md behind marker comments. rsconstruct treats a declared output_file as
build output and deletes it before regenerating, which for a part-hand-written
file means deleting the hand-written half. Splitting the two makes README.md
genuinely 100% generated and README.md.in a real, tracked input, which is also
what lets rsconstruct know when a rebuild is needed.

The same profiles.yaml feeds the About page of the veltzer.github.io site,
rendered there by that repo's own scripts/gen_profiles.py. Each repository
generates its own artifact from the shared source; neither writes into the
other.
"""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_REPO = REPO_ROOT.parent / "data"

SOURCE = DATA_REPO / "yaml" / "profiles.yaml"
TEMPLATE = REPO_ROOT / "README.md.in"
TARGET = REPO_ROOT / "README.md"

PLACEHOLDER = "{{ profiles }}"

# This page links to the site; the site does not link to itself, which is why
# this lives here rather than in the shared YAML.
MAIN_PROFILE_URL = "https://veltzer.github.io"

BANNER = (
    "<!-- Generated from README.md.in and ../data/yaml/profiles.yaml.\n"
    "     Do not edit this file: run `rsconstruct build` instead. -->"
)


def die(message):
    """Print an error to stderr and exit non-zero."""
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def load_groups():
    """Load and validate the profile groups from the shared YAML source."""
    if not SOURCE.is_file():
        die(f"Missing source file {SOURCE}. Clone the data repo alongside this one.")
    data = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if not data.get("groups"):
        die(f"{SOURCE} has no 'groups' key")
    return data


def render(data):
    """Render the whole shared block as markdown.

    Contact line, intro, the link list, then the trailing extras. The site's
    About page renders the same fields in the same order from the same file,
    so the two pages show the same thing; only this page's title and the
    view-counter comment stay in README.md.in as local prose.
    """
    lines = []

    contact = data.get("contact")
    if contact:
        badge = f"![{contact['badge_alt']}]({contact['badge_url']})"
        lines.append(f"{contact['text_en']} [{badge}]({contact['url']})")
        lines.append("")

    intro = data.get("intro")
    if intro:
        lines.append(intro["text_en"])
        lines.append("")

    lines.append(f"* [main profile]({MAIN_PROFILE_URL})")
    lines.append("")

    for group in data["groups"]:
        lines.append(f"### {group['title_en']}")
        lines.append("")
        for item in group["items"]:
            lines.append(f"* [{item['name']}]({item['url']})")
            for child in item.get("children", []):
                # Two spaces, not four: rumdl's MD007 wants indent depth 1 at
                # two spaces, and this file is linted like any other markdown.
                lines.append(f"  * [{child['name']}]({child['url']})")
        lines.append("")

    for extra in data.get("extras", []):
        if extra.get("id") == "viewcounter":
            # Keep the explanatory comment attached to the counter it explains.
            lines.append("[//1]: <> (The next link is number of views of my profile)")
            lines.append("")
        lines.append(render_extra(extra))
        lines.append("")

    return "\n".join(lines).rstrip("\n")


def render_extra(extra):
    """Render one trailing extra: a sentence with a link, or a linked badge."""
    if "badge_url" in extra:
        badge = f"![{extra['badge_alt']}]({extra['badge_url']})"
        # The view counter is a bare badge with no link to wrap it.
        body = f"[{badge}]({extra['url']})" if "url" in extra else badge
        return f"### {body}" if extra.get("heading") else body
    return f"{extra['text_en']} [{extra['link_text_en']}]({extra['url']})"


def main():
    """Render the template with the profile links and write README.md."""
    if not TEMPLATE.is_file():
        die(f"Missing template {TEMPLATE}")
    template = TEMPLATE.read_text(encoding="utf-8")
    if PLACEHOLDER not in template:
        die(f"{TEMPLATE} has no {PLACEHOLDER} placeholder")

    body = template.replace(PLACEHOLDER, render(load_groups()))
    TARGET.write_text(f"{BANNER}\n\n{body}", encoding="utf-8")
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
