#!/usr/bin/env python

"""
Render README.md -- the GitHub profile page -- from README.md.in and
../data/yaml/profiles.yaml.

GitHub serves README.md straight from the default branch of this repository, so
it is a committed artifact rather than throwaway build output: there is no
deploy step, and a push is the publish.

That is why the hand-written prose lives in README.md.in rather than in
README.md behind marker comments. rsconstruct treats a declared output_file as
build output and deletes it before regenerating, which for a part-hand-written
file means deleting the hand-written half. Splitting the two makes README.md
genuinely 100% generated and README.md.in a real, tracked input, which is also
what lets rsconstruct know when a rebuild is needed.

The same profiles.yaml feeds the About page of the veltzer.github.io site,
rendered there by that repo's own scripts/gen_profiles.py. Each repository
generates its own artifact from the shared source; neither writes into the
other.
"""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_REPO = REPO_ROOT.parent / "data"

SOURCE = DATA_REPO / "yaml" / "profiles.yaml"
TEMPLATE = REPO_ROOT / "README.md.in"
TARGET = REPO_ROOT / "README.md"

PLACEHOLDER = "{{ profiles }}"

BANNER = (
    "<!-- Generated from README.md.in and ../data/yaml/profiles.yaml.\n"
    "     Do not edit this file: run `rsconstruct build` instead. -->"
)


def die(message):
    """Print an error to stderr and exit non-zero."""
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def load_groups():
    """Load and validate the profile groups from the shared YAML source."""
    if not SOURCE.is_file():
        die(f"Missing source file {SOURCE}. Clone the data repo alongside this one.")
    data = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    groups = data.get("groups")
    if not groups:
        die(f"{SOURCE} has no 'groups' key")
    return groups


def render(groups):
    """Render the link list as markdown.

    Unlike the site, this renders every entry. The github_only flag exists to
    keep things off the public site that are fine here -- the keybr profiles are
    named for mail addresses that are already public on this page.
    """
    lines = []
    for group in groups:
        lines.append(f"### {group['title_en']}")
        lines.append("")
        for item in group["items"]:
            lines.append(f"* [{item['name']}]({item['url']})")
            for child in item.get("children", []):
                # Two spaces, not four: rumdl's MD007 wants indent depth 1 at
                # two spaces, and this file is linted like any other markdown.
                lines.append(f"  * [{child['name']}]({child['url']})")
        lines.append("")
    return "\n".join(lines).rstrip("\n")


def main():
    """Render the template with the profile links and write README.md."""
    if not TEMPLATE.is_file():
        die(f"Missing template {TEMPLATE}")
    template = TEMPLATE.read_text(encoding="utf-8")
    if PLACEHOLDER not in template:
        die(f"{TEMPLATE} has no {PLACEHOLDER} placeholder")

    body = template.replace(PLACEHOLDER, render(load_groups()))
    TARGET.write_text(f"{BANNER}\n\n{body}", encoding="utf-8")
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
